---
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - 'pinned'
  - 'security'
  - 'help wanted'
# Label to use when marking an issue as stale
staleLabel: 'stale'
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: >
  This issue has been automatically closed because it has not had
  recent activity, but it can be reopened.
  Thank you for your contributions.
