dist: bionic
language: php
os: linux

php:
    - 7.3
    - 7.4
## Cache composer
cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - source .travis/xdebug.sh
    - xdebug-disable
    - pecl install ast-1.0.4
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
    - .travis/phpcs.sh
    - vendor/bin/phan
    - xdebug-enable
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - bash <(curl -s https://codecov.io/bash)
