dist: trusty
language: php

php:
    - 7.2
    - 7.3

sudo: false

## Cache composer
cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - pecl install ast-1.0.4
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
    - vendor/bin/phan

after_script:
    - |
        if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        fi
