version: '3.7'
services:
  php:
    image: ghcr.io/open-telemetry/opentelemetry-php/opentelemetry-php-base:${PHP_VERSION:-8.0}
    volumes:
    - ./:/usr/src/myapp
    - ./:/usr/src/open-telemetry/
    user: "${PHP_USER}:root"
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG:-''}
