services:
  php:
    image: ghcr.io/open-telemetry/opentelemetry-php/opentelemetry-php-base:${PHP_VERSION:-8.1}
    volumes:
    - ./:/usr/src/myapp
    user: "${PHP_USER}:root"
    env_file:
      - .env
  zipkin:
    image: openzipkin/zipkin-slim:3.6.1@sha256:fc29b9862c14f4fc241cf0259c585e1cfd4e9b18f01ad36d86adaabb7d01815c
    ports:
    - 9411:9411
  jaeger:
    image: jaegertracing/jaeger:2.19.0@sha256:ede4864215be4cd85bd8c3129a2fea6c5713c5653c7282c429dba123014bc68b
    ports:
    - 9412:9412
    - 16686:16686
  collector:
    image: otel/opentelemetry-collector-contrib:0.156.0@sha256:125bdbeb7590cc1952c5b3430ecf14063568980c2c93d5b38676cc0446ed8108
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./files/collector/otel-collector-config.yml:/etc/otel-collector-config.yml
