version: '3.7'
services:
  prometheus:
    image: prom/prometheus@sha256:3c42b892cf723fa54d2f262c37a0e1f80aa8c8ddb1da7b9b0df9455a35a7f893
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  redis:
    image: redis@sha256:234c902a2db49461a129e2d4aeff85b28cf20187ed274a67f6e50995fa713c7b
    ports:
        - 6379:6379
  web:
    image: nginx:alpine@sha256:54f2a904c251d5a34adf545a72d32515a15e08418dae0266e23be2e18c66fefa
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./docker/examples/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build:
      context: .
      dockerfile: docker/examples/Dockerfile
      args:
        - PHP_VERSION=8.0-fpm
        - EXT_ENABLE=redis
    volumes:
      - ./examples/prometheus/index.php:/var/www/public/index.php
      - ./:/php
    depends_on:
      - redis
      - prometheus
