services:
  php:
    image: ghcr.io/open-telemetry/opentelemetry-php/opentelemetry-php-base:${PHP_VERSION:-8.1}
    volumes:
    - ./:/usr/src/myapp
    user: "${PHP_USER}:root"
    env_file:
      - .env
  zipkin:
    image: openzipkin/zipkin-slim:3.6.1@sha256:fc29b9862c14f4fc241cf0259c585e1cfd4e9b18f01ad36d86adaabb7d01815c
    ports:
    - 9411:9411
  jaeger:
    image: jaegertracing/jaeger:2.22.0@sha256:836b967b5abcf1f7758066aa6b348619267a2f1459f72d472840570f9bd88a17
    ports:
    - 9412:9412
    - 16686:16686
  collector:
    image: otel/opentelemetry-collector-contrib:0.162.0@sha256:39923a8e431bd1f57be82411999d389fcfe40857492e4365456d97a4c1f74be6
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./files/collector/otel-collector-config.yml:/etc/otel-collector-config.yml
