services:
  phpdoc:
    image: phpdoc/phpdoc:3@sha256:312ebf61ed88a6ea79aac768e43c9e9af0dd5bf3e710ed6d40ab8e53bfeeb121
    volumes:
      - ./:/data
  preview:
    image: nginx:alpine@sha256:5616878291a2eed594aee8db4dade5878cf7edcb475e59193904b198d9b830de
    ports:
      - 8080:80
    volumes:
      - ./docs/build:/usr/share/nginx/html