<?php

declare(strict_types=1);

namespace Jaeger\Thrift\Crossdock;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Exception\TProtocolException;
use Thrift\Type\TType;

class JoinTraceRequest
{
    public static $isValidate = false;

    public static $_TSPEC = [
        1 => [
            'var' => 'serverRole',
            'isRequired' => true,
            'type' => TType::STRING,
        ],
        2 => [
            'var' => 'downstream',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Crossdock\Downstream',
        ],
    ];

    /**
     * @var string
     */
    public $serverRole = null;
    /**
     * @var \Jaeger\Thrift\Crossdock\Downstream
     */
    public $downstream = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['serverRole'])) {
                $this->serverRole = $vals['serverRole'];
            }
            if (isset($vals['downstream'])) {
                $this->downstream = $vals['downstream'];
            }
        }
    }

    public function getName()
    {
        return 'JoinTraceRequest';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->serverRole);
                    } else {
                        $xfer += $input->skip($ftype);
                    }

                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->downstream = new \Jaeger\Thrift\Crossdock\Downstream();
                        $xfer += $this->downstream->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }

                    break;
                default:
                    $xfer += $input->skip($ftype);

                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();

        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('JoinTraceRequest');
        if ($this->serverRole !== null) {
            $xfer += $output->writeFieldBegin('serverRole', TType::STRING, 1);
            $xfer += $output->writeString($this->serverRole);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->downstream !== null) {
            if (!is_object($this->downstream)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('downstream', TType::STRUCT, 2);
            $xfer += $this->downstream->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();

        return $xfer;
    }
}
