<?php
namespace Jaeger\Thrift\Crossdock;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class StartTraceRequest extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'serverRole',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'sampled',
            'isRequired' => true,
            'type' => TType::BOOL,
        ),
        3 => array(
            'var' => 'baggage',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'downstream',
            'isRequired' => true,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Crossdock\Downstream',
        ),
    );

    /**
     * @var string
     */
    public $serverRole = null;
    /**
     * @var bool
     */
    public $sampled = null;
    /**
     * @var string
     */
    public $baggage = null;
    /**
     * @var \Jaeger\Thrift\Crossdock\Downstream
     */
    public $downstream = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'StartTraceRequest';
    }


    public function read($input)
    {
        return $this->_read('StartTraceRequest', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('StartTraceRequest', self::$_TSPEC, $output);
    }

}
