<?php
namespace Jaeger\Thrift\Crossdock;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface TracedServiceIf
{
    /**
     * @param \Jaeger\Thrift\Crossdock\StartTraceRequest $request
     * @return \Jaeger\Thrift\Crossdock\TraceResponse Each server must include the information about the span it observed.
     * It can only be omitted from the response if notImplementedError field is not empty.
     * If the server was instructed to make a downstream call, it must embed the
     * downstream response in its own response.
     * 
     */
    public function startTrace(\Jaeger\Thrift\Crossdock\StartTraceRequest $request);
    /**
     * @param \Jaeger\Thrift\Crossdock\JoinTraceRequest $request
     * @return \Jaeger\Thrift\Crossdock\TraceResponse Each server must include the information about the span it observed.
     * It can only be omitted from the response if notImplementedError field is not empty.
     * If the server was instructed to make a downstream call, it must embed the
     * downstream response in its own response.
     * 
     */
    public function joinTrace(\Jaeger\Thrift\Crossdock\JoinTraceRequest $request);
}
