<?php
namespace Jaeger\Thrift\Crossdock;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Each server must include the information about the span it observed.
 * It can only be omitted from the response if notImplementedError field is not empty.
 * If the server was instructed to make a downstream call, it must embed the
 * downstream response in its own response.
 */
class TraceResponse
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'span',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Crossdock\ObservedSpan',
        ),
        2 => array(
            'var' => 'downstream',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Jaeger\Thrift\Crossdock\TraceResponse',
        ),
        3 => array(
            'var' => 'notImplementedError',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var \Jaeger\Thrift\Crossdock\ObservedSpan
     */
    public $span = null;
    /**
     * @var \Jaeger\Thrift\Crossdock\TraceResponse
     */
    public $downstream = null;
    /**
     * @var string
     */
    public $notImplementedError = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['span'])) {
                $this->span = $vals['span'];
            }
            if (isset($vals['downstream'])) {
                $this->downstream = $vals['downstream'];
            }
            if (isset($vals['notImplementedError'])) {
                $this->notImplementedError = $vals['notImplementedError'];
            }
        }
    }

    public function getName()
    {
        return 'TraceResponse';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->span = new \Jaeger\Thrift\Crossdock\ObservedSpan();
                        $xfer += $this->span->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->downstream = new \Jaeger\Thrift\Crossdock\TraceResponse();
                        $xfer += $this->downstream->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->notImplementedError);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('TraceResponse');
        if ($this->span !== null) {
            if (!is_object($this->span)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('span', TType::STRUCT, 1);
            $xfer += $this->span->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->downstream !== null) {
            if (!is_object($this->downstream)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('downstream', TType::STRUCT, 2);
            $xfer += $this->downstream->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->notImplementedError !== null) {
            $xfer += $output->writeFieldBegin('notImplementedError', TType::STRING, 3);
            $xfer += $output->writeString($this->notImplementedError);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
