FROM php:7.2-buster
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
RUN chmod +x /usr/local/bin/composer
RUN composer install
RUN pecl install ast-1.0.4
RUN echo "extension=ast.so" >> /usr/local/etc/php/conf.d/docker-php-ext-ast.ini
ENTRYPOINT ["./vendor/bin/phan"]
