<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/profiles/v1development/profiles.proto

namespace Opentelemetry\Proto\Profiles\V1development;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A Stack represents a stack trace as a list of locations.
 *
 * Generated from protobuf message <code>opentelemetry.proto.profiles.v1development.Stack</code>
 */
class Stack extends \Google\Protobuf\Internal\Message
{
    /**
     * References to locations in ProfilesDictionary.location_table.
     * The first location is the leaf frame.
     *
     * Generated from protobuf field <code>repeated int32 location_indices = 1;</code>
     */
    private $location_indices;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $location_indices
     *           References to locations in ProfilesDictionary.location_table.
     *           The first location is the leaf frame.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opentelemetry\Proto\Profiles\V1Development\Profiles::initOnce();
        parent::__construct($data);
    }

    /**
     * References to locations in ProfilesDictionary.location_table.
     * The first location is the leaf frame.
     *
     * Generated from protobuf field <code>repeated int32 location_indices = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocationIndices()
    {
        return $this->location_indices;
    }

    /**
     * References to locations in ProfilesDictionary.location_table.
     * The first location is the leaf frame.
     *
     * Generated from protobuf field <code>repeated int32 location_indices = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocationIndices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->location_indices = $arr;

        return $this;
    }

}

