<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/trace/v1/trace.proto

namespace Opentelemetry\Proto\Trace\V1\Status;

/**
 * Protobuf type <code>opentelemetry.proto.trace.v1.Status.DeprecatedStatusCode</code>
 */
class DeprecatedStatusCode
{
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_OK = 0;</code>
     */
    const DEPRECATED_STATUS_CODE_OK = 0;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_CANCELLED = 1;</code>
     */
    const DEPRECATED_STATUS_CODE_CANCELLED = 1;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_UNKNOWN_ERROR = 2;</code>
     */
    const DEPRECATED_STATUS_CODE_UNKNOWN_ERROR = 2;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_INVALID_ARGUMENT = 3;</code>
     */
    const DEPRECATED_STATUS_CODE_INVALID_ARGUMENT = 3;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_DEADLINE_EXCEEDED = 4;</code>
     */
    const DEPRECATED_STATUS_CODE_DEADLINE_EXCEEDED = 4;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_NOT_FOUND = 5;</code>
     */
    const DEPRECATED_STATUS_CODE_NOT_FOUND = 5;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_ALREADY_EXISTS = 6;</code>
     */
    const DEPRECATED_STATUS_CODE_ALREADY_EXISTS = 6;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_PERMISSION_DENIED = 7;</code>
     */
    const DEPRECATED_STATUS_CODE_PERMISSION_DENIED = 7;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_RESOURCE_EXHAUSTED = 8;</code>
     */
    const DEPRECATED_STATUS_CODE_RESOURCE_EXHAUSTED = 8;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_FAILED_PRECONDITION = 9;</code>
     */
    const DEPRECATED_STATUS_CODE_FAILED_PRECONDITION = 9;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_ABORTED = 10;</code>
     */
    const DEPRECATED_STATUS_CODE_ABORTED = 10;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_OUT_OF_RANGE = 11;</code>
     */
    const DEPRECATED_STATUS_CODE_OUT_OF_RANGE = 11;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_UNIMPLEMENTED = 12;</code>
     */
    const DEPRECATED_STATUS_CODE_UNIMPLEMENTED = 12;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_INTERNAL_ERROR = 13;</code>
     */
    const DEPRECATED_STATUS_CODE_INTERNAL_ERROR = 13;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_UNAVAILABLE = 14;</code>
     */
    const DEPRECATED_STATUS_CODE_UNAVAILABLE = 14;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_DATA_LOSS = 15;</code>
     */
    const DEPRECATED_STATUS_CODE_DATA_LOSS = 15;
    /**
     * Generated from protobuf enum <code>DEPRECATED_STATUS_CODE_UNAUTHENTICATED = 16;</code>
     */
    const DEPRECATED_STATUS_CODE_UNAUTHENTICATED = 16;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DeprecatedStatusCode::class, \Opentelemetry\Proto\Trace\V1\Status_DeprecatedStatusCode::class);

