<?php

declare(strict_types=1);

namespace Jaeger\Thrift\Agent;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

interface SamplingManagerIf
{
    /**
     * @param string $serviceName
     * @return \Jaeger\Thrift\Agent\SamplingStrategyResponse
     */
    public function getSamplingStrategy($serviceName);
}
