<?php

declare(strict_types=1);

namespace Jaeger\Thrift\Agent;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

interface ThrottlingServiceIf
{
    /**
     * @param string[] $serviceNames
     * @return \Jaeger\Thrift\Agent\ThrottlingResponse
     */
    public function getThrottlingConfigs(array $serviceNames);
}
