<?php
namespace Jaeger\Thrift\Agent;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ThrottlingConfig extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'maxOperations',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'creditsPerSecond',
            'isRequired' => true,
            'type' => TType::DOUBLE,
        ),
        3 => array(
            'var' => 'maxBalance',
            'isRequired' => true,
            'type' => TType::DOUBLE,
        ),
    );

    /**
     * @var int
     */
    public $maxOperations = null;
    /**
     * @var double
     */
    public $creditsPerSecond = null;
    /**
     * @var double
     */
    public $maxBalance = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'ThrottlingConfig';
    }


    public function read($input)
    {
        return $this->_read('ThrottlingConfig', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('ThrottlingConfig', self::$_TSPEC, $output);
    }

}
