<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/metrics/v1/metrics.proto

namespace Opentelemetry\Proto\Metrics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * IntHistogramDataPoint is deprecated; use HistogramDataPoint.
 * This is a single data point in a timeseries that describes
 * the time-varying values of a Histogram of int values. A Histogram contains
 * summary statistics for a population of values, it may optionally contain
 * the distribution of those values across a set of buckets.
 * If the histogram contains the distribution of values, then both
 * "explicit_bounds" and "bucket counts" fields must be defined.   
 * If the histogram does not contain the distribution of values, then both
 * "explicit_bounds" and "bucket_counts" must be omitted and only "count" and
 * "sum" are known.
 *
 * Generated from protobuf message <code>opentelemetry.proto.metrics.v1.IntHistogramDataPoint</code>
 */
class IntHistogramDataPoint extends \Google\Protobuf\Internal\Message
{
    /**
     * The set of labels that uniquely identify this timeseries.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.StringKeyValue labels = 1;</code>
     */
    private $labels;
    /**
     * start_time_unix_nano is the last time when the aggregation value was reset
     * to "zero". For some metric types this is ignored, see data types for more
     * details.
     * The aggregation value is over the time interval (start_time_unix_nano,
     * time_unix_nano].
     * 
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January
     * 1970.
     * Value of 0 indicates that the timestamp is unspecified. In that case the
     * timestamp may be decided by the backend.
     *
     * Generated from protobuf field <code>fixed64 start_time_unix_nano = 2;</code>
     */
    private $start_time_unix_nano = 0;
    /**
     * time_unix_nano is the moment when this aggregation value was reported.
     * 
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January
     * 1970.
     *
     * Generated from protobuf field <code>fixed64 time_unix_nano = 3;</code>
     */
    private $time_unix_nano = 0;
    /**
     * count is the number of values in the population. Must be non-negative. This
     * value must be equal to the sum of the "count" fields in buckets if a
     * histogram is provided.
     *
     * Generated from protobuf field <code>fixed64 count = 4;</code>
     */
    private $count = 0;
    /**
     * sum of the values in the population. If count is zero then this field
     * must be zero. This value must be equal to the sum of the "sum" fields in
     * buckets if a histogram is provided.
     *
     * Generated from protobuf field <code>sfixed64 sum = 5;</code>
     */
    private $sum = 0;
    /**
     * bucket_counts is an optional field contains the count values of histogram
     * for each bucket.
     * The sum of the bucket_counts must equal the value in the count field.
     * The number of elements in bucket_counts array must be by one greater than
     * the number of elements in explicit_bounds array.
     *
     * Generated from protobuf field <code>repeated fixed64 bucket_counts = 6;</code>
     */
    private $bucket_counts;
    /**
     * explicit_bounds specifies buckets with explicitly defined bounds for values.
     * This defines size(explicit_bounds) + 1 (= N) buckets. The boundaries for
     * bucket at index i are:
     * (-infinity, explicit_bounds[i]] for i == 0
     * (explicit_bounds[i-1], explicit_bounds[i]] for 0 < i < N-1
     * (explicit_bounds[i], +infinity) for i == N-1
     * 
     * The values in the explicit_bounds array must be strictly increasing.
     * Histogram buckets are inclusive of their upper boundary, except the last
     * bucket where the boundary is at infinity. This format is intentionally
     * compatible with the OpenMetrics histogram definition.
     *
     * Generated from protobuf field <code>repeated double explicit_bounds = 7;</code>
     */
    private $explicit_bounds;
    /**
     * (Optional) List of exemplars collected from
     * measurements that were used to form the data point
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.metrics.v1.IntExemplar exemplars = 8;</code>
     */
    private $exemplars;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opentelemetry\Proto\Common\V1\StringKeyValue[]|\Google\Protobuf\Internal\RepeatedField $labels
     *           The set of labels that uniquely identify this timeseries.
     *     @type int|string $start_time_unix_nano
     *           start_time_unix_nano is the last time when the aggregation value was reset
     *           to "zero". For some metric types this is ignored, see data types for more
     *           details.
     *           The aggregation value is over the time interval (start_time_unix_nano,
     *           time_unix_nano].
     *           
     *           Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January
     *           1970.
     *           Value of 0 indicates that the timestamp is unspecified. In that case the
     *           timestamp may be decided by the backend.
     *     @type int|string $time_unix_nano
     *           time_unix_nano is the moment when this aggregation value was reported.
     *           
     *           Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January
     *           1970.
     *     @type int|string $count
     *           count is the number of values in the population. Must be non-negative. This
     *           value must be equal to the sum of the "count" fields in buckets if a
     *           histogram is provided.
     *     @type int|string $sum
     *           sum of the values in the population. If count is zero then this field
     *           must be zero. This value must be equal to the sum of the "sum" fields in
     *           buckets if a histogram is provided.
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $bucket_counts
     *           bucket_counts is an optional field contains the count values of histogram
     *           for each bucket.
     *           The sum of the bucket_counts must equal the value in the count field.
     *           The number of elements in bucket_counts array must be by one greater than
     *           the number of elements in explicit_bounds array.
     *     @type float[]|\Google\Protobuf\Internal\RepeatedField $explicit_bounds
     *           explicit_bounds specifies buckets with explicitly defined bounds for values.
     *           This defines size(explicit_bounds) + 1 (= N) buckets. The boundaries for
     *           bucket at index i are:
     *           (-infinity, explicit_bounds[i]] for i == 0
     *           (explicit_bounds[i-1], explicit_bounds[i]] for 0 < i < N-1
     *           (explicit_bounds[i], +infinity) for i == N-1
     *           
     *           The values in the explicit_bounds array must be strictly increasing.
     *           Histogram buckets are inclusive of their upper boundary, except the last
     *           bucket where the boundary is at infinity. This format is intentionally
     *           compatible with the OpenMetrics histogram definition.
     *     @type \Opentelemetry\Proto\Metrics\V1\IntExemplar[]|\Google\Protobuf\Internal\RepeatedField $exemplars
     *           (Optional) List of exemplars collected from
     *           measurements that were used to form the data point
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opentelemetry\Proto\Metrics\V1\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * The set of labels that uniquely identify this timeseries.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.StringKeyValue labels = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * The set of labels that uniquely identify this timeseries.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.StringKeyValue labels = 1;</code>
     * @param \Opentelemetry\Proto\Common\V1\StringKeyValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opentelemetry\Proto\Common\V1\StringKeyValue::class);
        $this->labels = $arr;

        return $this;
    }

    /**
     * start_time_unix_nano is the last time when the aggregation value was reset
     * to "zero". For some metric types this is ignored, see data types for more
     * details.
     * The aggregation value is over the time interval (start_time_unix_nano,
     * time_unix_nano].
     * 
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January
     * 1970.
     * Value of 0 indicates that the timestamp is unspecified. In that case the
     * timestamp may be decided by the backend.
     *
     * Generated from protobuf field <code>fixed64 start_time_unix_nano = 2;</code>
     * @return int|string
     */
    public function getStartTimeUnixNano()
    {
        return $this->start_time_unix_nano;
    }

    /**
     * start_time_unix_nano is the last time when the aggregation value was reset
     * to "zero". For some metric types this is ignored, see data types for more
     * details.
     * The aggregation value is over the time interval (start_time_unix_nano,
     * time_unix_nano].
     * 
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January
     * 1970.
     * Value of 0 indicates that the timestamp is unspecified. In that case the
     * timestamp may be decided by the backend.
     *
     * Generated from protobuf field <code>fixed64 start_time_unix_nano = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTimeUnixNano($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_time_unix_nano = $var;

        return $this;
    }

    /**
     * time_unix_nano is the moment when this aggregation value was reported.
     * 
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January
     * 1970.
     *
     * Generated from protobuf field <code>fixed64 time_unix_nano = 3;</code>
     * @return int|string
     */
    public function getTimeUnixNano()
    {
        return $this->time_unix_nano;
    }

    /**
     * time_unix_nano is the moment when this aggregation value was reported.
     * 
     * Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January
     * 1970.
     *
     * Generated from protobuf field <code>fixed64 time_unix_nano = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeUnixNano($var)
    {
        GPBUtil::checkUint64($var);
        $this->time_unix_nano = $var;

        return $this;
    }

    /**
     * count is the number of values in the population. Must be non-negative. This
     * value must be equal to the sum of the "count" fields in buckets if a
     * histogram is provided.
     *
     * Generated from protobuf field <code>fixed64 count = 4;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * count is the number of values in the population. Must be non-negative. This
     * value must be equal to the sum of the "count" fields in buckets if a
     * histogram is provided.
     *
     * Generated from protobuf field <code>fixed64 count = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * sum of the values in the population. If count is zero then this field
     * must be zero. This value must be equal to the sum of the "sum" fields in
     * buckets if a histogram is provided.
     *
     * Generated from protobuf field <code>sfixed64 sum = 5;</code>
     * @return int|string
     */
    public function getSum()
    {
        return $this->sum;
    }

    /**
     * sum of the values in the population. If count is zero then this field
     * must be zero. This value must be equal to the sum of the "sum" fields in
     * buckets if a histogram is provided.
     *
     * Generated from protobuf field <code>sfixed64 sum = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSum($var)
    {
        GPBUtil::checkInt64($var);
        $this->sum = $var;

        return $this;
    }

    /**
     * bucket_counts is an optional field contains the count values of histogram
     * for each bucket.
     * The sum of the bucket_counts must equal the value in the count field.
     * The number of elements in bucket_counts array must be by one greater than
     * the number of elements in explicit_bounds array.
     *
     * Generated from protobuf field <code>repeated fixed64 bucket_counts = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBucketCounts()
    {
        return $this->bucket_counts;
    }

    /**
     * bucket_counts is an optional field contains the count values of histogram
     * for each bucket.
     * The sum of the bucket_counts must equal the value in the count field.
     * The number of elements in bucket_counts array must be by one greater than
     * the number of elements in explicit_bounds array.
     *
     * Generated from protobuf field <code>repeated fixed64 bucket_counts = 6;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBucketCounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FIXED64);
        $this->bucket_counts = $arr;

        return $this;
    }

    /**
     * explicit_bounds specifies buckets with explicitly defined bounds for values.
     * This defines size(explicit_bounds) + 1 (= N) buckets. The boundaries for
     * bucket at index i are:
     * (-infinity, explicit_bounds[i]] for i == 0
     * (explicit_bounds[i-1], explicit_bounds[i]] for 0 < i < N-1
     * (explicit_bounds[i], +infinity) for i == N-1
     * 
     * The values in the explicit_bounds array must be strictly increasing.
     * Histogram buckets are inclusive of their upper boundary, except the last
     * bucket where the boundary is at infinity. This format is intentionally
     * compatible with the OpenMetrics histogram definition.
     *
     * Generated from protobuf field <code>repeated double explicit_bounds = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExplicitBounds()
    {
        return $this->explicit_bounds;
    }

    /**
     * explicit_bounds specifies buckets with explicitly defined bounds for values.
     * This defines size(explicit_bounds) + 1 (= N) buckets. The boundaries for
     * bucket at index i are:
     * (-infinity, explicit_bounds[i]] for i == 0
     * (explicit_bounds[i-1], explicit_bounds[i]] for 0 < i < N-1
     * (explicit_bounds[i], +infinity) for i == N-1
     * 
     * The values in the explicit_bounds array must be strictly increasing.
     * Histogram buckets are inclusive of their upper boundary, except the last
     * bucket where the boundary is at infinity. This format is intentionally
     * compatible with the OpenMetrics histogram definition.
     *
     * Generated from protobuf field <code>repeated double explicit_bounds = 7;</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExplicitBounds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->explicit_bounds = $arr;

        return $this;
    }

    /**
     * (Optional) List of exemplars collected from
     * measurements that were used to form the data point
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.metrics.v1.IntExemplar exemplars = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExemplars()
    {
        return $this->exemplars;
    }

    /**
     * (Optional) List of exemplars collected from
     * measurements that were used to form the data point
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.metrics.v1.IntExemplar exemplars = 8;</code>
     * @param \Opentelemetry\Proto\Metrics\V1\IntExemplar[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExemplars($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opentelemetry\Proto\Metrics\V1\IntExemplar::class);
        $this->exemplars = $arr;

        return $this;
    }

}

