<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/collector/logs/v1/logs_service.proto

namespace GPBMetadata\Opentelemetry\Proto\Collector\Logs\V1;

class LogsService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Opentelemetry\Proto\Logs\V1\Logs::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8d040a386f70656e74656c656d657472792f70726f746f2f636f6c6c65" .
            "63746f722f6c6f67732f76312f6c6f67735f736572766963652e70726f74" .
            "6f12256f70656e74656c656d657472792e70726f746f2e636f6c6c656374" .
            "6f722e6c6f67732e7631225c0a184578706f72744c6f6773536572766963" .
            "655265717565737412400a0d7265736f757263655f6c6f67731801200328" .
            "0b32292e6f70656e74656c656d657472792e70726f746f2e6c6f67732e76" .
            "312e5265736f757263654c6f6773221b0a194578706f72744c6f67735365" .
            "7276696365526573706f6e7365329d010a0b4c6f67735365727669636512" .
            "8d010a064578706f7274123f2e6f70656e74656c656d657472792e70726f" .
            "746f2e636f6c6c6563746f722e6c6f67732e76312e4578706f72744c6f67" .
            "7353657276696365526571756573741a402e6f70656e74656c656d657472" .
            "792e70726f746f2e636f6c6c6563746f722e6c6f67732e76312e4578706f" .
            "72744c6f677353657276696365526573706f6e736522004286010a28696f" .
            "2e6f70656e74656c656d657472792e70726f746f2e636f6c6c6563746f72" .
            "2e6c6f67732e763142104c6f67735365727669636550726f746f50015a46" .
            "6769746875622e636f6d2f6f70656e2d74656c656d657472792f6f70656e" .
            "74656c656d657472792d70726f746f2f67656e2f676f2f636f6c6c656374" .
            "6f722f6c6f67732f7631620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

