<?php

declare(strict_types=1);

namespace Jaeger\Thrift;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

interface CollectorIf
{
    /**
     * @param \Jaeger\Thrift\Batch[] $batches
     * @return \Jaeger\Thrift\BatchSubmitResponse[]
     */
    public function submitBatches(array $batches);
}
