#!/usr/bin/env bash

# Install Symfony
curl -sS https://get.symfony.com/cli/installer | bash
mv /root/.symfony/bin/symfony /usr/local/bin/symfony

# Set up Symfony test application
cd tests/TraceContext/W3CTestService
rm -rf test_app
composer create-project symfony/skeleton test_app

# Move our files into the test application
cp index.php test_app/public/index.php
cp TestController.php test_app/src/Controller/TestController.php
cd test_app

composer require annotations

# Link the local opentelemetry changes to vendor/open-telemetry
composer require open-telemetry/opentelemetry "*"
composer config repositories.local \
    '{"type": "path", "url": "/usr/src/open-telemetry/", "options": {"symLink": true }}' \
    --file composer.json
rm composer.lock
composer clearcache
composer install

# Start the server to start listening in the background
symfony server:start -d --port=8001

# Setup the TraceContext Test Service
apt-get install -y python3-pip 
pip3 install aiohttp

cd ..
rm -rf trace-context
git clone https://github.com/w3c/trace-context.git

cd trace-context/test

# Run the test
python3 test.py http://127.0.0.1:8001/test
