<?php

declare(strict_types=1);

namespace Jaeger\Thrift\Agent\Zipkin;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

interface ZipkinCollectorIf
{
    /**
     * @param \Jaeger\Thrift\Agent\Zipkin\Span[] $spans
     * @return \Jaeger\Thrift\Agent\Zipkin\Response[]
     */
    public function submitZipkinBatch(array $spans);
}
