<?php

// DO NOT EDIT, this is an Auto-generated file from script/semantic-conventions

declare(strict_types=1);

namespace OpenTelemetry\SemConv\Incubating\Attributes;

/**
 * Semantic attributes and corresponding values for rpc.
 * @see https://opentelemetry.io/docs/specs/semconv/registry/attributes/rpc/
 * May contain @experimental Semantic Conventions which may change or be removed in the future.
 */
interface RpcIncubatingAttributes
{
    /**
     * The fully-qualified logical name of the method from the RPC interface perspective.
     * The method name MAY have unbounded cardinality in edge or error cases.
     *
     * Some RPC frameworks or libraries provide a fixed set of recognized methods
     * for client stubs and server implementations. Instrumentations for such
     * frameworks MUST set this attribute to the original method name only
     * when the method is recognized by the framework or library.
     *
     * When the method is not recognized, for example, when the server receives
     * a request for a method that is not predefined on the server, or when
     * instrumentation is not able to reliably detect if the method is predefined,
     * the attribute MUST be set to `_OTHER`.
     *
     * If the RPC instrumentation could end up converting valid RPC methods to
     * `_OTHER`, then it SHOULD provide a way to configure the list of recognized
     * RPC methods.
     *
     * The `rpc.method` can be different from the name of any implementing
     * method/function.
     * The `code.function.name` attribute may be used to record the fully-qualified
     * method actually executing the call on the server side, or the
     * RPC client stub method on the client side.
     *
     * @experimental
     */
    public const RPC_METHOD = 'rpc.method';

    /**
     * The original name of the method used by the client.
     *
     * @experimental
     */
    public const RPC_METHOD_ORIGINAL = 'rpc.method_original';

    /**
     * RPC request metadata, `<key>` being the normalized RPC metadata key (lowercase), the value being the metadata values.
     *
     * Instrumentations SHOULD require an explicit configuration of which metadata values are to be captured.
     * Including all request metadata values can be a security risk - explicit configuration helps avoid leaking sensitive information.
     *
     * For example, a property `my-custom-key` with value `["1.2.3.4", "1.2.3.5"]` SHOULD be recorded as
     * `rpc.request.metadata.my-custom-key` attribute with value `["1.2.3.4", "1.2.3.5"]`
     *
     * @experimental
     */
    public const RPC_REQUEST_METADATA = 'rpc.request.metadata';

    /**
     * RPC response metadata, `<key>` being the normalized RPC metadata key (lowercase), the value being the metadata values.
     *
     * Instrumentations SHOULD require an explicit configuration of which metadata values are to be captured.
     * Including all response metadata values can be a security risk - explicit configuration helps avoid leaking sensitive information.
     *
     * For example, a property `my-custom-key` with value `["attribute_value"]` SHOULD be recorded as
     * the `rpc.response.metadata.my-custom-key` attribute with value `["attribute_value"]`
     *
     * @experimental
     */
    public const RPC_RESPONSE_METADATA = 'rpc.response.metadata';

    /**
     * Status code of the RPC returned by the RPC server or generated by the client
     * Usually it represents an error code, but may also represent partial success, warning, or differentiate between various types of successful outcomes.
     * Semantic conventions for individual RPC frameworks SHOULD document what `rpc.status_code` means in the context of that system and which values are considered to represent errors.
     *
     * @experimental
     */
    public const RPC_STATUS_CODE = 'rpc.status_code';

    /**
     * The Remote Procedure Call (RPC) system.
     * The client and server RPC systems may differ for the same RPC interaction. For example, a client may use Apache Dubbo or Connect RPC to communicate with a server that uses gRPC since both protocols provide compatibility with gRPC.
     *
     * @experimental
     */
    public const RPC_SYSTEM_NAME = 'rpc.system.name';

    /**
     * [gRPC](https://grpc.io/)
     * @experimental
     */
    public const RPC_SYSTEM_NAME_VALUE_GRPC = 'grpc';

    /**
     * [Apache Dubbo](https://dubbo.apache.org/)
     * @experimental
     */
    public const RPC_SYSTEM_NAME_VALUE_DUBBO = 'dubbo';

    /**
     * [Connect RPC](https://connectrpc.com/)
     * @experimental
     */
    public const RPC_SYSTEM_NAME_VALUE_CONNECTRPC = 'connectrpc';

    /**
     * [JSON-RPC](https://www.jsonrpc.org/)
     * @experimental
     */
    public const RPC_SYSTEM_NAME_VALUE_JSONRPC = 'jsonrpc';

}
